# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a15e8deb5abf491baa125f8d7a9a50fc567b1a702e1f718a8b6146688053a3aebee2498f0fef69b7e4f8665e02ffa08ab8db0683520a77b4eebb0aab510aae3e

test:
  secret_key_base: c4c18ad24064a1cf952c1263ea2b02c5aeabc3b87b6ae9c1f577679bb655fe37f719f7d9bd4eb06b874709f4bf48baa4aab8628e1bfe8a1fa3737680d622afa8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
